#+title: vertico.el - Changelog
#+author: Daniel Mendler
#+language: en

* Version 1.3 (2023-04-25)

- =vertico-grid-annotate= and =vertico-flat-annotate=: New customization variables
  to enable annotations in grid and flat display mode.
- =vertico-buffer-display=: Add more choices for the display action to the
  customizable variable.
- =vertico--history-hash=: Deprioritize current file when sorting by history.
- Fix sorting by history position for =project-find-file=.

* Version 1.2 (2023-03-11)

- =vertico-buffer=: Inherit =cursor-type= in minibuffer window, instead of always
  using the =box= cursor type. This change is particularly useful for Evil users,
  where the cursor reflect the Evil editing state.
- =vertico-indexed=: Fix a regression introduced in version 1.1.
- Use =natnum= custom type, ported back by the Compat package, version 29.1.4.0.

* Version 1.1 (2023-02-17)

- Add =vertico-preselect= configuration option.
- =vertico-directory-up= moves up even if point is not located directly after /.
- Use =cl-defgeneric= internally as mechanism to allow extensions to override
  functionality, e.g., the candidate formatting and display.
- =vertico-multiform-mode=: Add =vertico-multiform-map= with default key bindings.

* Version 1.0 (2022-12-22)

- Emacs 29: Add support for =REQUIRE-MATCH= functions
- =vertico-directory-enter=: Handle selection of ./ and ../ candidates specially.

* Version 0.29 (2022-11-22)

- Start of changelog.
